LD = i386-elf-ld
LDFLAGS = --Ttext 0x6400000 \
		  -m elf_i386       \
		  -e kmain          \

CXX = i386-elf-gcc
CXXFLAGS = -m32                 \
		   -g                   \
		   -std=c++14           \
		   -nostdlib            \
		   -nostdinc            \
		   -fno-builtin         \
		   -fno-stack-protector \
		   -fno-pic             \
		   -fno-rtti            \
		   -fno-exceptions      \
		   -Wall -Wextra        \
		   -Ilibcxx/include     \
		   -Ilibc/include

OBJCOPY = i386-elf-objcopy